In [15]:
import torch

In [17]:
scalars = torch.tensor([7])
print(scalars, scalars.ndim, scalars.shape)

tensor([7]) 1 torch.Size([1])


In [18]:
vector = torch.tensor([1,2,3])
print(vector,vector.ndim,vector.shape)

tensor([1, 2, 3]) 1 torch.Size([3])


In [19]:
matrix = torch.tensor([[1,2],[3,4]])
print(matrix, matrix.ndim, matrix.shape)

tensor([[1, 2],
        [3, 4]]) 2 torch.Size([2, 2])


In [20]:
tensor_3d = torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]])
print(tensor_3d,tensor_3d.ndim,tensor_3d.shape)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]]) 3 torch.Size([2, 2, 2])


In [21]:
#create tensor from a list

data = [[1,2,3],[2,3,4]]
tensor_list = torch.tensor(data)
print(tensor_list,tensor_list.shape)

tensor([[1, 2, 3],
        [2, 3, 4]]) torch.Size([2, 3])


In [22]:
#create tensor from numpy array

import numpy as np

np_array = np.array(data)
print(np_array)

np_tensor = torch.from_numpy(np_array)
print(np_tensor,np_tensor.shape)

[[1 2 3]
 [2 3 4]]
tensor([[1, 2, 3],
        [2, 3, 4]]) torch.Size([2, 3])


In [28]:
# Direct creation
zeros = torch.zeros((2, 3))       # all zeros
ones = torch.ones((2, 3,3))         # all ones
rand = torch.rand((2, 3,3,4))         # random numbers (0–1)

print(ones)
print(zeros)
print(rand)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[[[0.1284, 0.3873, 0.4010, 0.7277],
          [0.8496, 0.8646, 0.3889, 0.8232],
          [0.3937, 0.0893, 0.9219, 0.5973]],

         [[0.6607, 0.9731, 0.9671, 0.9316],
          [0.9574, 0.8499, 0.3460, 0.5272],
          [0.2591, 0.5493, 0.3196, 0.4903]],

         [[0.5863, 0.7937, 0.0903, 0.5127],
          [0.3827, 0.9048, 0.2042, 0.7489],
          [0.5938, 0.0657, 0.2730, 0.3484]]],


        [[[0.6997, 0.3320, 0.0231, 0.2782],
          [0.5322, 0.8034, 0.8115, 0.4403],
          [0.1208, 0.1415, 0.4105, 0.4535]],

         [[0.9007, 0.6739, 0.0060, 0.5914],
          [0.3327, 0.6970, 0.5030, 0.5184],
          [0.0299, 0.9158, 0.1403, 0.6682]],

         [[0.2686, 0.5671, 0.8896, 0.9896],
          [0.9852, 0.5136, 0.2731, 0.5140],
          [0.6062, 0.6159, 0.3607, 0.3996]]]])


In [29]:
tensor = torch.rand((3, 4), dtype=torch.float32)

print(f"Shape: {tensor.shape}")
print(f"Datatype: {tensor.dtype}")
print(f"Device: {tensor.device}")


Shape: torch.Size([3, 4])
Datatype: torch.float32
Device: cpu


In [30]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print(a + b)      # elementwise add
print(a * b)      # elementwise multiply
print(a @ b)      # dot product (vector multiplication)


tensor([5, 7, 9])
tensor([ 4, 10, 18])
tensor(32)


In [35]:
# requires_grad=True tells PyTorch to track operations
x = torch.tensor(2.0, requires_grad=True)

y = x ** 2        # y = x^2
y.backward()      # compute gradient dy/dx

print(x.grad)     # Should print 4 (since dy/dx = 2x = 4 when x=2)
print(x)

tensor(4.)
tensor(2., requires_grad=True)


In [38]:
x = torch.tensor(3.0, requires_grad=True)
z = torch.tensor(4.0, requires_grad=True)

y = x * z + z ** 2   # y = xz + z²
diff = y.backward()

print(diff)

print(x.grad)   # dy/dx = z = 4
print(z.grad)   # dy/dz = x + 2z = 3 + 8 = 11


None
tensor(4.)
tensor(11.)


In [40]:
import torch

# Define the function as a series of PyTorch operations
x = torch.tensor(3.0, requires_grad=True)
y = x**2

# We can see the function and its value
print(f"The function is y = x^2, where x = {x.item()}")
print(f"The value of y is: {y.item()}")

# This computes the derivative, which is dy/dx = 2x.
# At x=3, the derivative is 2*3 = 6.
y.backward()

# We can access the numerical value of the derivative at x=3
print(f"The numerical derivative at x=3 is: {x.grad.item()}")

The function is y = x^2, where x = 3.0
The value of y is: 9.0
The numerical derivative at x=3 is: 6.0


In [41]:
import torch

# Define x with requires_grad=True
x = torch.tensor(2.0, requires_grad=True)

# First function: y = x^2
y = x**2

# First derivative: dy/dx = 2x
# To get the second derivative, we need to save the graph
# The create_graph=True argument builds a new graph for the backward pass
grad_1 = torch.autograd.grad(y, x, create_graph=True)[0]

# Now compute the second derivative
# The second derivative is d^2y/dx^2 = d(2x)/dx = 2
grad_2 = torch.autograd.grad(grad_1, x)[0]

print(f"The first derivative (2x) at x=2 is: {grad_1.item()}")
print(f"The second derivative (2) is: {grad_2.item()}")

The first derivative (2x) at x=2 is: 4.0
The second derivative (2) is: 2.0
